#ifndef SQLITESAVE_GLOBAL_H
#define SQLITESAVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQLITESAVE_LIBRARY)
#  define SQLITESAVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQLITESAVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQLITESAVE_GLOBAL_H
